Update serializers.py
Fixed compatibility with `django-axes` error.

```
TypeError: AxesProxyHandler.user_logged_in() missing 1 required positional argument: 'request'
```

According to `django-axes`:
```
Authenticating users¶
Axes needs a request attribute to be supplied to the stock Django authenticate method in the django.contrib.auth module in order to function correctly.
```
https://django-axes.readthedocs.io/en/latest/3_usage.html